### PR TITLE
Authentication.2

### PR DESCRIPTION
**Pull request by MarcOverZero**
finishes authentication

### CODE REVIEW

**Comment by Mcents** [comment]
This looks good Marc. Ready to merge to master!

**Comment by vaidashi** [comment]
Should we define the admin in the controller?

**Comment by MarcOverZero** [comment]
@vaidashi yes, but we should TDD that up when we do authorization.

**Comment by vaidashi** [comment]
Got it.

**Comment by JF-Lalonde** [comment]
Let's add a confirm password field to the create user form before merging this

**Comment by MarcOverZero** [comment]
Good catch, thank you. Password confirmation is now added.

**Pull request merged**
