### PR TITLE
User crud functions

### PR DESCRIPTION
**Pull request by Mcents**
Two Tests Passing
-User Account Creation
-User Logging In and Out

I didn't touch authorization or authentication. Users can't delete or edit accounts yet.

### CODE REVIEW

**Comment by JF-Lalonde** [comment]
Did you mean "factory girl" instead of "foundation girl"?

**Comment by JF-Lalonde** [comment]
Looks good otherwise. @MarcOverZero will have to add a role attribute to users and will begin to work on authentication and authorization today

**Comment by JF-Lalonde** [comment]
We will work on editing/deleting users as well

**Comment by MarcOverZero** [comment]
Glad you fired up with Factory Girl, I need practice

**Pull request merged**
